### ISSUE TITLE
Files larger than 2 GB failed to unZip

### ISSUE THREAD

**Issue by e3bmo3ty** [appcelerator-modules/ti.compression#16]
it logs error failed to extract file and it may be password protected (its not)

**Comment by e3bmo3ty** [comment]
**Any Updates ?.... still stuck at the same error**

**Comment by janvennemann** [comment]
Closing out older issues. Please check with the latest 2.0.0 release and let us know if the issue persists.

**Comment by e3bmo3ty** [comment]
@janvennemann still the same error "Failed to extract archive file [{file path}] , may be password protected
