### ISSUE TITLE
iOS 64 bit support is missing.

### ISSUE THREAD

**Issue by speedyankur** [appcelerator-modules/ti.compression#5]
We have been using your Compression Module since Ti SDK 3.1, but now we have to support iOS x64 architecture. So we upgraded our app to TI SDK 3.5 and it started giving me this error:-
[ERROR] :  Script Error Couldn't find module: ti.compression for architecture: x86_64

I believe we need to upgrade this module in-order to support Ti SDK 3.5. Can you please help us on this.

**Comment by ingo** [comment]
Look here: https://github.com/appcelerator-modules/ti.compression/releases
